#spring.application.name=BattleshipServer

spring.datasource.url=jdbc:mysql://localhost:3306/battleship_game
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.username=root
spring.datasource.password=yuval12345
spring.jpa.hibernate.ddl-auto=update
