package com.battleship.BattleshipServer.logic;

import com.battleship.BattleshipServer.model.Board;
import com.battleship.BattleshipServer.model.game.Game;
import com.battleship.BattleshipServer.model.User;
import com.battleship.BattleshipServer.model.ship.Ship;

import java.util.UUID;

/*
*  This class is responsible for generating unique ids for the different objects in the game.
*  The ids are generated by concatenating a prefix with a random string.
* */
public class IdGenerator {
    private final static String  DB_USER_PREFIX = "game-";
    private final static String DB_GAME_PREFIX = "user-";
    private final static String DB_BOARD_PREFIX = "board-";
    private final static String DB_SHIP_PREFIX = "ship-";

    public static String generate(Object object) {
        String retVal;

        String afterPrefixId = generateAfterPrefixId();

        if (object instanceof Game) {
            retVal = DB_USER_PREFIX + afterPrefixId;
        } else if (object instanceof User) {
            retVal = DB_GAME_PREFIX + afterPrefixId;
        } else if (object instanceof Board) {
            retVal = DB_BOARD_PREFIX + afterPrefixId;
        } else if (object instanceof Ship) {
            retVal = DB_SHIP_PREFIX + afterPrefixId;
        } else {
            throw new RuntimeException("Undefined object type: " + object.getClass().getName());
        }

        return retVal;
    }

    /*
    *  This method generates a random string that will be concatenated to the prefix.
    * */
    private static String generateAfterPrefixId() {
        String retVal;

        UUID uuid = UUID.randomUUID();
        String uuidString = uuid.toString().replace("-", "");
        retVal = uuidString.substring(0, 10);

        return retVal;
    }
}
